@baseUrl = http://localhost:3000
@moderationSecret = superSecret123
@random_identifier = 123e4567-e89b-12d3-a456-426614174000


POST {{baseUrl}}/rices
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Mi primer zenrice
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.zenrice"
Content-Type: text/plain

This is an example zenrice file.
------WebKitFormBoundary7MA4YWxkTrZu0gW--