@baseUrl = http://localhost:3000

# {
#     "key": "value",
#     "description": "Example content"
# }

# {'key':'value','description':'Example content'}

POST {{baseUrl}}/rices
Content-Type: application/json

{
  "name": "cool-zenrice-aurora",
  "content": "{'key':'value','description':'Example content'}"
}

