@baseUrl = http://localhost:3000
@previous_slug = cool-zenrice-aurora-ef732cbc-fdde-4f76-b4e3-cff0ec8b6f39
@previous_token = b406f962-5c51-43a9-8382-40e0983a46e7

# {
#     "key": "value",
#     "description": "Example updated content"
# }

# {'key':'value','description':'Example updated content'}

PUT {{baseUrl}}/rices/{{previous_slug}}
Content-Type: application/json
x-rices-token: {{previous_token}}

{
  "content": "{'key':'value','description':'Example updated content'}"
}

