@baseUrl = http://localhost:3000
@previous_slug = cool-zenrice-aurora2-1d1e74b3-8d6d-40ea-bd4f-a6f4ad893f88
@previous_token = be4545f4-d92b-416c-8b3b-50cc9a49dee9

# {
#     "key": "value",
#     "description": "Example updated content"
# }

# {'key':'value','description':'Example updated content'}

PUT {{baseUrl}}/rices/{{previous_slug}}
Content-Type: application/json
x-rices-token: {{previous_token}}

{
  "content": "{'key':'value','description':'Example updated content'}"
}

