@baseUrl = http://localhost:3000
@previous_slug = cool-zenrice-aurora2-b970a742-789c-4349-8a4d-da63c8bbe77d
@previous_token = 03fbfdb4-d3a5-4d64-8740-feac7d32e7a8

DELETE {{baseUrl}}/rices/{{previous_slug}}
x-rices-token: {{previous_token}}
