@baseUrl = http://localhost:3000
@previous_slug = my-first-zenrice-b7b94d24-ecb6-4495-93de-ba85be2e3052
@previous_token = 6181664b-00e8-4eef-8e23-1f7fa0c64021

DELETE {{baseUrl}}/rices/{{previous_slug}}
x-rices-token: {{previous_token}}
